### ISSUE TITLE
Make it possible to use the search-select within a mat-form-field element

### ISSUE THREAD

**Issue by danger89** [OasisDigital/angular-material-search-select#6]
Hi Kyle,

Let's start with an excuse that I maybe spam too much, which is not my intention at all :heart: , but hopefully you agree this item is a real issue.

I would like to use `search-select` within the Angular Material `mat-form-fied`, just like my normal `mat-select` elements.

When I try to use your search-select within a mat-form-field, I currently get the error:
> mat-form-field must contain a MatFormFieldControl

For example it would be nice if I still could this this search-select like so:
```html
 <mat-form-field>
        <search-select ...></search-select>
        <mat-icon matPrefix>credit_card</mat-icon>
 </mat-form-fied>
```

Kind regards,
Melroy van den Berg

**Comment by kylecordes** [comment]
Hello. It would be delightful for what you described to be possible, but it currently is not. The reason is subtle and perhaps irritating, but it is a feature of the web platform. Take a look at this code, this is for the search select control bundled in the library:

https://github.com/OasisDigital/angular-material-search-select/blob/master/src/app/search-select/search-select.component.html

Also this code, this is for an example in this repo, that shows how you can build your own control using the base class provided by this project:

https://github.com/OasisDigital/angular-material-search-select/blob/master/src/app/select-company-css-table/select-company-css-table.component.html

In both of these, the template for the component includes the <mat-form-field> as well as the <input>. This is critical, because the CSS shipped by Angular Material requires it. CSS would "notice" an extra layer of HTML/DOM in the kind of example you wrote:

```
 <mat-form-field>
        <search-select ...></search-select>
        <mat-icon matPrefix>credit_card</mat-icon>
 </mat-form-fied>
```

... In the CSS would not apply correctly. In fact, this is how I first tried to implement this library, to be used exactly as you describe. But after trying many variations, it is unworkable.

The short answer of how to achieve what you're looking for is to work off of the example I linked above:

https://github.com/OasisDigital/angular-material-search-select/tree/master/src/app/select-company-css-table

The nice thing about this is that you only need to build your own HTML template. Look at the component definition for what I just linked above, you need to copy and paste some annotation boilerplate but the actual class implementation is empty.

```
@Component({
  selector: 'obs-select-company-css-table',
  templateUrl: './select-company-css-table.component.html',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => SelectCompanyCssTableComponent),
      multi: true
    }
  ],
  styles: [],
  encapsulation: ViewEncapsulation.None
})
export class SelectCompanyCssTableComponent extends SearchSelectBase {
}
```

**Comment by kylecordes** [comment]
(see explanation above)
